# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bd17b59744dd9415354c1e01a0dbb7ceedfda3a8791b3fcdae3df5d39ed5de82f06d89386ada5578887f5059b7d73f1492e32be9176b3ff9150e6965e908c17

test:
  secret_key_base: 19a13b81d604b8cb7577fc99fe1b9b3d1fa64d54540db1575863a1127eb13bf53d435908d902f47d5e0b729d74b1f66275559024422aeed4dc76e0b740f14ad8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
